### ISSUE TITLE
ACK failure

### ISSUE THREAD

**Issue by Norgul** [stomp-php/stomp-php#147]
What is the purpose of `ack()` method? I can't send acknowledgement because `read()` also deletes a message from queue, resulting in ACK error: `AMQ339025 failed to ack because no message with id 2,147,492,461`.

Is this correct behavior?

**Comment by danesteve** [comment]
You should subscribe using the `client` or `client-individual` ack mode ([example](https://github.com/stomp-php/stomp-php-examples/blob/4c6974511b5758b8d93fe8eca91e30bebdb85f95/src/connectivity.php#L34)), otherwise the messages get [automatically deleted](https://stomp.github.io/stomp-specification-1.2.html#SUBSCRIBE_ack_Header).

**Comment by Norgul** [comment]
Oh...thanks. Is that covered anywhere in the lib documentation?

**Comment by danesteve** [comment]
You can find more info in the links i posted in my last comment.

Simply changing:
```php
$stomp->subscribe('destination');
```
to:
```php
$stomp->subscribe('destination', null, 'client-individual');
```
should do the trick.

**Comment by Norgul** [comment]
It did the trick, but I don't know how could I know what the parameters do unless it is written in the documentation (or digging deeper in code) :) 
Anyway, it's working. Thanks

**Comment by staabm** [comment]
> It did the trick, but I don't know how could I know what the parameters do unless it is written in the documentation (or digging deeper in code) :)

feel free to send a PR with doc improvements
